services:
  # Development
  d: &commons
    build:
      context: "."
      target: "${MIX_ENV:-dev}"
      args:
        RELEASE_NAME: "${RELEASE_NAME:-storage}"
    image: "${DOCKER_IMAGE_NAME:-kv-dev}"
    stdin_open: true
    entrypoint: ["/bin/bash", "run.sh", "_dev"]
    user: "kv"
    env_file: "${DOCKER_ENV_FILE:-.env}"
    ports:
      - "${DOCKER_HOST_PORT}:4000"
    volumes:
      - ".:/app"
      - "not_used__build:/app/_build/"
      - "not_used_deps:/app/deps/"
      - "not_used_.elixir_ls:/app/.elixir_ls/"
    networks:
      kv-dev:

  # test
  t:
    <<: *commons
    volumes:
      - ".:/app"
      - "not_used__build_test:/app/_build/"
      - "not_used_deps_test:/app/deps/"
      - "not_used_.elixir_ls_test:/app/.elixir_ls/"
    networks:
      kv-test:

  # Production
  p:
    <<: *commons
    entrypoint: ["/app/bin/run", "start"]
    # Volume mappings is not needed in production in case we want to run
    # production image with docker compose
    volumes:
      - "not_used:/app/"
    networks:
      kv-release:

volumes:
  not_used__build:
  not_used_deps:
  not_used_.elixir_ls:
  not_used__build_test:
  not_used_deps_test:
  not_used_.elixir_ls_test:
  not_used:

networks:
  kv-dev:
    driver: bridge
    name: kv-dev
  kv-release:
    driver: bridge
    name: kv-release
  kv-test:
    driver: bridge
    name: kv-test
